Repository fossasia/labyrinth, pull requests merged in 2018-11, with the labels that each got.

#786 Fixes #785 : Update Readme Links
  README.md
Labels: documentation

#820 [Fixed #815] Added timer, and suitable translations
  css/custom.css
  index.html
  js/player.js
  js/translate.js
Labels: new feature

#829 Update PR Template to accomodate Change Location
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#801 Fix Missing Wall for Blood Tile
  js/tiles.js
  tiles/rooms/wall/bloodsidewall2.svg
Labels: close if not updated (GC 1)

#831 Deploy Status Bage to Readme
  README.md
Labels: enhancement

#830 Adding Repo Size Badge
  README.md
Labels: enhancement

#828 Add new wall
  js/levels.js
  js/tiles.js
  tiles/rooms/door/quirky.svg
  tiles/rooms/door/redDoor.svg
  tiles/rooms/floor/quirky.svg
  tiles/rooms/wall/quirky.svg
Labels: help wanted

#823 Add a wall
  js/levels.js
  js/tiles.js
  tiles/rooms/wall/redright.svg
Labels: help wanted
